## Vectorization 

In [1]:
import sys
print(sys.version)
import numpy as np
print(np.__version__)

3.6.2rc2 (v3.6.2rc2:8913311345, Jul  7 2017, 00:35:45) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
1.13.1


In [2]:
np.random.seed(20)

In [3]:
npa = np.random.randint(0,50,20000)

I have touched on the values of vectorization in the last couple of videos. To review, the true power of vectorization lies in two properties:

- Concise
- Efficient

The fundamental idea behind array programming is that operations apply at once to an entire set of values. This makes it a high-level programming model as it allows the programmer to think and operate on whole aggregates of data without having to resort to explicit loops of individual scalar operations.

You can read more here:
https://en.wikipedia.org/wiki/Array_programming

In [4]:
npa

array([35, 26, 15, ..., 36, 30, 26])

In [13]:
lsa = list(range(0,10))

As we have touched on, with vectorization we can apply changes to the entire array extremely efficiently, no more for loops. If we want to double the array, we just multiply by 2; if we want to cube it we just cube it.

In [7]:
npa * 2

array([70, 52, 30, ..., 72, 60, 52])

In [14]:
lsa * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
npa ** 3

array([42875, 17576,  3375, ..., 46656, 27000, 17576])

In [17]:
lsa ** 3

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
npa ** 2 ** 3

array([2251875390625,  208827064576,    2562890625, ..., 2821109907456,
        656100000000,  208827064576])

We can actually take this a step further and define our own vectorized functions, which will operate extremeley efficiently. Let's say that we need to do a series of transformations. We can include these in a function to make them a bit more readable.

We can simply declare exactly what we want done to each value.

In [19]:
def transformation(val):
    return ((val * 2) - 1)

In [20]:
transformation(2)

3

And then we can apply it to an array.

In [21]:
transformation(npa)

array([69, 51, 29, ..., 71, 59, 51])

While this did work, sometimes it will not, such as if we include filters or have specific transformations for certain values. In those cases we need to use the `vectorize` function in order to allow us to pass an array into it.

In [22]:
transform_2 = np.vectorize(transformation)

In [23]:
transform_2(npa)

array([69, 51, 29, ..., 71, 59, 51])

In [25]:
%timeit [transformation(x) for x in npa]

10.8 ms ± 429 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%timeit transform_2(npa)

3.99 ms ± 71.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


We can see that in this case it was not faster than a list comprehension. However, remember that this is just a small, simple array; when we get to more complicated arrays and matrices, things will certainly change.

## Multidimensional Arrays

We learned in the last video how to generate simple arrays. Now let’s move on to arrays with multiple dimensions. Think in terms of matrices or cubes.

We can create these by reshaping one-dimensional arrays. One of the simplest ways to do this is with the reshape command. That gives us an `x` by `y` array.

In [27]:
npa = np.arange(25)

In [28]:
npa2 = npa.reshape((5,5))
npa2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

To create a null matrix we can use the zeros command along with the desired shape.

In [29]:
np.zeros((5,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [30]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

What's nice about this is that a lot of outputs can be used as inputs.

In [31]:
np.zeros(npa2.shape)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

This obviously works because it outputs a tuple.

In [34]:
npa2.shape

(5, 5)

Now these have all been two-dimensional arrays. Let's explore the third dimension.

In [20]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Of course, when we start diving into theory, we can start going to higher and higher dimensions. Here is the fourth dimension.

In [33]:
np.zeros((4,4,4,4))

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.

For the most part, we will be working in two dimensions. Just be aware that NumPy is capable of representing more dimensions. Now you are going to see a lot of these things come together. You are likely going to enjoy vectorization and Boolean selection after this section.

First I will set a seed so you can get exactly the same results that I do. A seed is a number that goes into the computer's process for simulating random numbers.  Although these are meant to look as close to random as possible, if you and I set the same seed, we will get the same sequence of pseudorandom numbers.  A seed is what makes random reproducable.

In [38]:
np.random.seed(10)

In [39]:
npa2 = np.random.randint(1,10,25).reshape(5,5)
npa2

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]])

In [40]:
npa3 = np.random.randint(1,10,25).reshape(5,5)
npa3

array([[5, 3, 7, 8, 9],
       [9, 3, 1, 7, 8],
       [9, 2, 8, 2, 5],
       [1, 9, 6, 5, 8],
       [9, 9, 3, 7, 3]])

Now let's say we want to multiple the first array by 2.

In [41]:
npa2 * 2

array([[10,  2,  4,  2,  4],
       [18,  2, 18, 14, 10],
       [ 8,  2, 10, 14, 18],
       [ 4, 18, 10,  4,  8],
       [14, 12,  8, 14,  4]])

Let's say we want to compare the values and see where array number 2 is greater than array number 3.

In [42]:
npa2 < npa3

array([[False,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True,  True,  True, False, False],
       [False, False,  True,  True,  True],
       [ True,  True, False, False,  True]], dtype=bool)

Isn't that surprisingly easy? Think about all the for loops you would have to write to achieve the same result.

We can also sum those values to get the total counts of where it is greater.

In [43]:
(npa2 > npa3).sum()

5

Or when they are equal.

In [44]:
(npa2 == npa3).sum()

5

Just like vectors, we can get mimimums and maximums extremely easily.

In [45]:
npa2.min()

1

In [46]:
npa2.argmin()

1

We can even do that by the axis or column.

In [37]:
npa2

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]])

In [38]:
npa2.max(axis=1) # by row

array([5, 9, 9, 9, 7])

In [39]:
npa2.max(axis=0) # by column

array([9, 9, 9, 7, 9])

There are also  plenty of other functions such as the transpose.

In [40]:
npa2.transpose()

array([[5, 9, 4, 2, 7],
       [1, 1, 1, 9, 6],
       [2, 9, 5, 5, 4],
       [1, 7, 7, 2, 7],
       [2, 5, 9, 4, 2]])

In [41]:
npa2.T

array([[5, 9, 4, 2, 7],
       [1, 1, 1, 9, 6],
       [2, 9, 5, 5, 4],
       [1, 7, 7, 2, 7],
       [2, 5, 9, 4, 2]])

In [42]:
npa2.T == npa2.transpose()

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

We can also multiple arrays very easily, which will do value-by-value multiplication but not any of the other products unless we are looking for another product.

In [36]:
npa2 * npa3

array([[40, 50,  7, 20, 20],
       [10, 10, 27, 70,  8],
       [81, 63, 50, 12,  1],
       [35, 56, 81,  4, 72],
       [10, 10,  4, 63, 36]])

We can also flatten and unravel the array. These look the same, but flatten returns a new array while unravel points to the old one.

In [49]:
np4 = npa2.flatten()
np4

array([25,  1,  2,  1,  2,  9,  1,  9,  7,  5,  4,  1,  5,  7,  9,  2,  9,
        5,  2,  4,  7,  6,  4,  7,  2])

In [44]:
np2[0] = 25

In [45]:
npa2

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]])

In [46]:
r = npa2.ravel()
r

array([5, 1, 2, 1, 2, 9, 1, 9, 7, 5, 4, 1, 5, 7, 9, 2, 9, 5, 2, 4, 7, 6, 4,
       7, 2])

In [47]:
r[0] = 25

In [48]:
npa2

array([[25,  1,  2,  1,  2],
       [ 9,  1,  9,  7,  5],
       [ 4,  1,  5,  7,  9],
       [ 2,  9,  5,  2,  4],
       [ 7,  6,  4,  7,  2]])

We can use some other helpful functions like cumsum and comprod to get the cumulative products and sums. This works for any dimensional array.

In [50]:
npa2.cumsum()

array([ 25,  26,  28,  29,  31,  40,  41,  50,  57,  62,  66,  67,  72,
        79,  88,  90,  99, 104, 106, 110, 117, 123, 127, 134, 136])

In [51]:
npa2.cumprod()

array([             25,              25,              50,              50,
                   100,             900,             900,            8100,
                 56700,          283500,         1134000,         1134000,
               5670000,        39690000,       357210000,       714420000,
            6429780000,     32148900000,     64297800000,    257191200000,
         1800338400000,  10802030400000,  43208121600000, 302456851200000,
       604913702400000])

That covers a lot of the basic functions you are going to use or need when working with pandas, but it is worth being aware that NumPy is a very deep library that does a lot more  than I have covered here. I wanted to cover these basics because they will come up when we work with pandas. Although this has likely felt fairly academic at this point, it provides a valuable foundation to pandas.